### ISSUE TITLE
another copy

### ISSUE THREAD

**Issue by GiantGlint** [sreechar/Windows95#17]

**Comment by sreechar** [comment]
?
this is an archive of windows 95 project. Please check the license and contributors list to learn more

**Comment by monke0192** [comment]
buddy if you want to archive this then you should *put the link to the original repo in the readme of this repository*

**Comment by GiantGlint** [comment]
This.

It's not extremely clear of the use of this repo, and it would be greatly appreciated if you could clearly state that it is an archive, rather then just upload the repo clone.
